### ISSUE TITLE
playtv@unifi

### ISSUE THREAD

**Issue by oma96ip** [weareblahs/epg#2]
Add, hypp sensasi,persona,dunia sinema

**Comment by weareblahs** [comment]
Will be adding source from unifi.com.my (same server as playtv.unifi.com.my) soon.

**Comment by oma96ip** [comment]
When you make a comeback.

Pada Ahd, 10 Jan 2021, 10:45 PTG Tan Yu Xuan <notifications@github.com>
menulis:

**Comment by weareblahs** [comment]
Because the link of playtv.unifi.com.my is encrypted, I had to update the EPG grabber (WebGrab+Plus) from my old (current version) to the latest version.

(Update from the main page stated below)
# UPDATE - 25/1/2020
I will be upgrading to the newest WebGrab+Plus Version (because some of the websites were encrypted) - this might take a long time to upgrade. 
<i> EPG will split as 4 parts for Astro and 2 parts for Freeview TV. </i>
<i> I will also combine all the EPGs as a link for importing. </i>

**Comment by oma96ip** [comment]
Awesome, thanks!

Pada Isn, 25 Jan 2021, 11:05 PTG Tan Yu Xuan <notifications@github.com>
menulis:
