### ISSUE TITLE
Missing EPG of unifitv.xml on 25/06/2021

### ISSUE THREAD

**Issue by ohsem** [weareblahs/epg#6]
unifitv.xml EPG list was override by the `GenerateDateStart` commit which discarded the unifitv.xml.
Check the commit on unifitv.xml.
<img width="1221" alt="Screenshot 2021-06-26 at 9 31 02 AM" src="https://user-images.githubusercontent.com/86503255/123497656-4bfd5f00-d661-11eb-9c04-4c540331852b.png">

**Comment by weareblahs** [comment]
The unifi TV EPG of 25/06/2021 is originally useless because of the "No Shows in Indexpage" error on playtv@unifi's website which made me clean this file. See image below for explanation:
![image](https://user-images.githubusercontent.com/37889443/123503182-e79fc700-d683-11eb-8e01-015ede671bf9.png)

Today's EPG will be back to normal.

**Comment by weareblahs** [comment]
Problem found on the config file - see weareblahs/epg for details about this.
